name: Bazel Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'bazel-build-system/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bazel
        uses: bazelbuild/setup-bazel@v3
        with:
          bazel-version: '4.1.0'

      - name: Build with Bazel
        run: bazel build //:app
        working-directory: bazel-build-system

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: bazel-build-system/bazel-bin/readme.pdf
